config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweet#index"
  resources :tweet, only: [:new, :create, :show] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord

  has_one_attached :image


  validates :nickname, presence: true
  validates :concept, presence: true
  validates :image, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
    else
      render :new
    end
  end

def show
    @tweet = Tweet.find(params[:id])
end

  private

  def tweet_params
    params.require(:tweet).permit(:nickname, :concept, :image)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweet_helper.rb
module TweetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dokkanonji</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweet/create.html.erb
<p>ありがとうございました。</p>
<p>正常に送信されました。</p>

app/views/tweet/index.html.erb
投稿画像一覧
<% if user_signed_in? && current_user.id %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>  


<div class="card">
  <% @tweets.each do |tweet| %>
        <ul class = "card_lists">
          <li><%= link_to image_tag(tweet.image),tweet_path(tweet.id) %></p>
              <div> ニックネーム</div>
              <%= tweet.nickname%></p>
              <div> コンセプト</div>
              <%= tweet.concept%></p>
            </li>
        </ul>
    <% end %>
</div>
<% else %>
  <%= link_to "ログイン", user_session_path %>
  <%= link_to "新規登録", new_user_registration_path %>
<% end %>

app/views/tweet/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
        <%= image_tag 'dokkanonji-image.png',class:"top-image"%>
        <%# 部分テンプレートでフォームを表示する %>


    <%= form_with url: tweet_index_path, model: @tweet, local: true do |f|%>
      <div class="field">
        <%= f.label :nickname, "ニックネーム" %><br />
        <%= f.text_field :nickname, class: :form__text, id:"tweet_nickname" %>
      </div>

      <div class="field">
        <%= f.label :image, "写真を選択してください" %><br />
        <%= f.file_field :image, id:"tweet_image" %>
      </div>


      <div class="field">
        <%= f.label :concept, "本日の物産展についてご意見・ご感想をお聞かせください" %><br />
        <%= f.text_area :concept, class: :form__text, id:"tweet_concept" %>
      </div>

     

      <div class="actions">
        <%= f.submit "送信する", class: :form__btn  %>
      </div>
    <% end %>


    </div>
  </div>
</div>

app/views/tweet/show.html.erb
<div class="show">  
  <ul >
    <li><%= image_tag @tweet.image,class: "show-image" %></p>
        <div> タイトル</div>
        <%= @tweet.title%></p>
        <div> ニックネーム</div>
        <%= @tweet.nickname%></p>
        <div> コンセプト</div>
        <%= @tweet.concept%></p>
      </li>
  </ul>
</div>